---
book_repo: pivotal-cf/docs-book-metric-store
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-metric-store
    ref: '1.0'
  directory: metric-store/1-0
  subnav_template: metric_store_1_0_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Metric Store
    search_placeholder: Search PCF Metric Store
    url_prefix: metric-store/1-0
    local_product_version: 1.0
    local_header_links: []